# Generated by Django 2.1 on 2018-11-19 19:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelNumber', models.PositiveIntegerField(default=0, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username_level', to='customer.Customer', to_field='account_no')),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999)])),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username_points', to='customer.Customer', to_field='account_no')),
            ],
        ),
        migrations.CreateModel(
            name='RewardLevelOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RewardLevelTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=256)),
                ('answer', models.CharField(blank=True, max_length=256)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username_survey', to='customer.Customer', to_field='account_no')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0, null=True)),
                ('sendTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_no_transaction', to='customer.Customer', to_field='account_no')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usernaME_transaction', to='customer.Customer', to_field='account_no')),
            ],
        ),
        migrations.AddField(
            model_name='rewardleveltwo',
            name='descriptionLevelTwo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewardLevelTwo', to='points.Rewards', to_field='description'),
        ),
        migrations.AddField(
            model_name='rewardlevelone',
            name='descriptionLevelOne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewardLevelOne', to='points.Rewards', to_field='description'),
        ),
    ]
